In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
df_granger = pd.read_csv('../data/processed/granger.csv')
df_decoding_region = pd.read_csv('../data/external/region_info.csv')
df_decoding_session_choice = pd.read_parquet('../data/external/choice_stage2.pqt')
df_decoding_session_stim = pd.read_parquet('../data/external/stimside_stage2.pqt')
df_decoding_session_feedback = pd.read_parquet('../data/external/feedback_stage2.pqt')

In [3]:
important_columns = ['Beryl', 'Beryl.1', 'Cosmos', 'Cosmos.1', '# recordings', '# neurons', '# good neurons', 'stim_dec','choice_dec','fback_dec','optBay_dec']

df_decoding_region = df_decoding_region[important_columns]

In [4]:
df_decoding_region = df_decoding_region.dropna()

In [16]:
df_decoding_region[df_decoding_region.Beryl=='LD']

,Beryl,Beryl.1,Cosmos,Cosmos.1,# recordings,# neurons,# good neurons,stim_dec,choice_dec,fback_dec,optBay_dec
118,LD,Lateral dorsal nucleus of thalamus,TH,Thalamus,21,1623,223,0.02,0.11,0.14,0.01

In [5]:
top_stim_regions = df_decoding_region.sort_values('stim_dec', ascending=False)[0:5]
top_choice_regions = df_decoding_region.sort_values('choice_dec', ascending=False)[0:5]
top_fback_regions = df_decoding_region.sort_values('fback_dec', ascending=False)[0:5]


bottom_stim_regions = df_decoding_region.sort_values('stim_dec', ascending=True)[0:5]
bottom_choice_regions = df_decoding_region.sort_values('choice_dec', ascending=True)[0:5]
bottom_fback_regions = df_decoding_region.sort_values('fback_dec', ascending=True)[0:5]

In [6]:
top_stim_regions

,Beryl,Beryl.1,Cosmos,Cosmos.1,# recordings,# neurons,# good neurons,stim_dec,choice_dec,fback_dec,optBay_dec
22,VISpm,posteromedial visual area,Isocortex,Isocortex,16,746,118,0.16,0.19,0.09,0.00
203,PRNc,Pontine reticular nucleus caudal part,HB,Hindbrain,7,507,63,0.11,0.29,0.42,0.03
264,IP,Interposed nucleus,CB,Cerebellum,23,1526,175,0.09,0.21,0.38,0.03
23,VISli,Laterointermediate area,Isocortex,Isocortex,8,494,60,0.09,0.07,0.12,0.01
98,VM,Ventral medial nucleus of the thalamus,TH,Thalamus,9,292,59,0.09,0.23,0.35,0.01

In [7]:
bottom_stim_regions

,Beryl,Beryl.1,Cosmos,Cosmos.1,# recordings,# neurons,# good neurons,stim_dec,choice_dec,fback_dec,optBay_dec
221,SPVI,Spinal nucleus of the trigeminal interpolar part,HB,Hindbrain,12,1819,66,-0.03,0.04,0.22,-0.01
66,ProS,Prosubiculum,HPF,Hippocampal formation,19,1482,200,-0.02,0.00,0.11,0.04
73,BLA,Basolateral amygdalar nucleus,CTXsp,Cortical subplate,10,1066,116,-0.02,-0.00,0.04,-0.00
5,SSp-ll,Primary somatosensory area lower limb,Isocortex,Isocortex,11,927,105,-0.02,0.06,0.23,0.07
61,ENTm,Entorhinal area medial part dorsal zone,HPF,Hippocampal formation,14,1521,195,-0.01,0.03,0.18,0.02

In [8]:
# top 5 and bottom 5; just to contrast
regions_we_want_data =  np.concatenate([top_stim_regions.Beryl.values,top_choice_regions.Beryl.values,top_fback_regions.Beryl.values,bottom_stim_regions.Beryl.values,bottom_choice_regions.Beryl.values,bottom_fback_regions.Beryl.values])

In [11]:
np.concatenate([top_stim_regions.Beryl.values,top_choice_regions.Beryl.values,top_fback_regions.Beryl.values])

array(['VISpm', 'PRNc', 'IP', 'VISli', 'VM', 'PRNc', 'GRN', 'VM', 'IP',
       'APN', 'PPN', 'AUDp', 'PAG', 'PRNc', 'IC'], dtype=object)

In [12]:
np.concatenate([bottom_stim_regions.Beryl.values,bottom_choice_regions.Beryl.values,bottom_fback_regions.Beryl.values])

array(['SPVI', 'ProS', 'BLA', 'SSp-ll', 'ENTm', 'COAp', 'EPd', 'ProS',
       'BLA', 'BMA', 'OT', 'PA', 'MEA', 'EPd', 'BLA'], dtype=object)

In [9]:
filter_regions = np.unique(regions_we_want_data)

In [10]:
filter_regions

array(['APN', 'AUDp', 'BLA', 'BMA', 'COAp', 'ENTm', 'EPd', 'GRN', 'IC',
       'IP', 'MEA', 'OT', 'PA', 'PAG', 'PPN', 'PRNc', 'ProS', 'SPVI',
       'SSp-ll', 'VISli', 'VISpm', 'VM'], dtype=object)

In [11]:
# now get eids from granger.csv

In [12]:
regions_we_want_data

array(['VISpm', 'PRNc', 'IP', 'VISli', 'VM', 'PRNc', 'GRN', 'VM', 'IP',
       'APN', 'PPN', 'AUDp', 'PAG', 'PRNc', 'IC', 'SPVI', 'ProS', 'BLA',
       'SSp-ll', 'ENTm', 'COAp', 'EPd', 'ProS', 'BLA', 'BMA', 'OT', 'PA',
       'MEA', 'EPd', 'BLA'], dtype=object)

In [14]:
eids = []
for x in df_granger[df_granger['source name'].isin(filter_regions)].sort_values('source #neur', ascending=False).groupby('source name'):
    eids.append(x[1][0:2].eid.values) # only top 2 eids

In [15]:
eids = np.concatenate([x for x in eids])

In [16]:
eids = np.unique(eids)

In [17]:
#download data now


from brainwidemap.bwm_loading import load_good_units
from one.api import ONE

c:\Users\debot\miniconda3\envs\info-decom\lib\site-packages\ibllib\atlas\__init__.py:205: DeprecationWarning: ibllib.atlas is deprecated. Please install iblatlas using "pip install iblatlas" and use this module instead
  warnings.warn('ibllib.atlas is deprecated. Please install iblatlas using "pip install iblatlas" and use '

In [18]:
one = ONE(base_url="https://openalyx.internationalbrainlab.org", password="international")

Connected to https://openalyx.internationalbrainlab.org as user "intbrainlab"

In [19]:
eids

array(['032ffcdf-7692-40b3-b9ff-8def1fc18b2e',
       '11163613-a6c9-4975-9586-84dc00481547',
       '239dd3c9-35f3-4462-95ee-91b822a22e6b',
       '2584ce3c-db10-4076-89cb-5d313138dd38',
       '25f77e81-c1af-46ab-8686-73ac3d67c4a7',
       '2e22c1fc-eec6-4856-85a0-7dba8668f646',
       '3e6a97d3-3991-49e2-b346-6948cb4580fb',
       '3f6e25ae-c007-4dc3-aa77-450fd5705046',
       '5386aba9-9b97-4557-abcd-abc2da66b863',
       '56956777-dca5-468c-87cb-78150432cc57',
       '6274dda8-3a59-4aa1-95f8-a8a549c46a26',
       '63c70ae8-4dfb-418b-b21b-f0b1e5fba6c9',
       '6b0b5d24-bcda-4053-a59c-beaa1fe03b8f',
       '872ce8ff-9fb3-485c-be00-bc5479e0095b',
       'a82800ce-f4e3-4464-9b80-4c3d6fade333',
       'aec5d3cc-4bb2-4349-80a9-0395b76f04e2',
       'c46b8def-620d-4d70-9397-be5694255f73',
       'c7bd79c9-c47e-4ea5-aea3-74dda991b48e',
       'c958919c-2e75-435d-845d-5b62190b520e',
       'cae5cd75-55e5-4277-8db3-cf4d6c5ff918',
       'd23a44ef-1402-4ed7-97f5-47e9a7a504d9',
       'da188f2c-553c-4e04-879b-c9ea2d1b9a93',
       'dda5fc59-f09a-4256-9fb5-66c67667a466',
       'f8d5c8b0-b931-4151-b86c-c471e2e80e5d',
       'fece187f-b47f-4870-a1d6-619afe942a7d'], dtype=object)

In [31]:
for idx in range(len(eids)):
    pids, probes = one.eid2pid(eids[idx])
    for pid in pids:
        spikes, clusters = load_good_units(one, pid)

In [32]:
# run GLM-HMM on eids
eids

array(['032ffcdf-7692-40b3-b9ff-8def1fc18b2e',
       '11163613-a6c9-4975-9586-84dc00481547',
       '239dd3c9-35f3-4462-95ee-91b822a22e6b',
       '2584ce3c-db10-4076-89cb-5d313138dd38',
       '25f77e81-c1af-46ab-8686-73ac3d67c4a7',
       '2e22c1fc-eec6-4856-85a0-7dba8668f646',
       '3e6a97d3-3991-49e2-b346-6948cb4580fb',
       '3f6e25ae-c007-4dc3-aa77-450fd5705046',
       '5386aba9-9b97-4557-abcd-abc2da66b863',
       '56956777-dca5-468c-87cb-78150432cc57',
       '6274dda8-3a59-4aa1-95f8-a8a549c46a26',
       '63c70ae8-4dfb-418b-b21b-f0b1e5fba6c9',
       '6b0b5d24-bcda-4053-a59c-beaa1fe03b8f',
       '872ce8ff-9fb3-485c-be00-bc5479e0095b',
       'a82800ce-f4e3-4464-9b80-4c3d6fade333',
       'aec5d3cc-4bb2-4349-80a9-0395b76f04e2',
       'c46b8def-620d-4d70-9397-be5694255f73',
       'c7bd79c9-c47e-4ea5-aea3-74dda991b48e',
       'c958919c-2e75-435d-845d-5b62190b520e',
       'cae5cd75-55e5-4277-8db3-cf4d6c5ff918',
       'd23a44ef-1402-4ed7-97f5-47e9a7a504d9',
       'da188f2c-553c-4e04-879b-c9ea2d1b9a93',
       'dda5fc59-f09a-4256-9fb5-66c67667a466',
       'f8d5c8b0-b931-4151-b86c-c471e2e80e5d',
       'fece187f-b47f-4870-a1d6-619afe942a7d'], dtype=object)

In [33]:
np.save('../data/processed/eids_with_detailed_insertions', eids)